# Site settings
title: "無定著"
description: "咣咣瞎扯淡"
podcast-description: "A legal place for neurodiverse humans."
url:  "" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "無定著"
  email: "wudingzhe@gmail.com"
#permalink: pretty
#permalink: /:title
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: Wudingzhe0
logo: /assets/img/Podcast_Cover.png
social:
  name: 咣咣
  links:
    - https://twitter.com/wudingzhe0
lang: CN

#Podcast Metadata. Used by the RSS Feed.
podcast_title: 咣咣瞎扯淡
podcast_author: 無定著
podcast_email: wudingzhe@gmail.com
podcast_subtitle: 少儿视角的外星观察调侃类播客
podcast_summary: 全宇宙首档少儿视角的外星观察调侃类播客。
podcast_description: 没个正经，满嘴瞎话，健脾养生。
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: cn
podcast_launch: "2020-11-25" #Launch date of your podcast
podcast_copyright: "2020 無定著; 2020 wudingzhe"
podcast_feed: https://wudingzhe.github.io/episodes.rss
podcast_artwork: "/assets/img/Podcast_Cover.png"